/**
 * Enum of all message type string values used in the Tank Royale protocol.
 * Values must match Java's Message.Type string values exactly.
 */
export enum MessageType {
  BotHandshake = "BotHandshake",
  ControllerHandshake = "ControllerHandshake",
  ObserverHandshake = "ObserverHandshake",
  ServerHandshake = "ServerHandshake",
  BotReady = "BotReady",
  BotIntent = "BotIntent",
  BotInfo = "BotInfo",
  BotListUpdate = "BotListUpdate",
  GameStartedEventForBot = "GameStartedEventForBot",
  GameStartedEventForObserver = "GameStartedEventForObserver",
  GameEndedEventForBot = "GameEndedEventForBot",
  GameEndedEventForObserver = "GameEndedEventForObserver",
  GameAbortedEvent = "GameAbortedEvent",
  GamePausedEventForObserver = "GamePausedEventForObserver",
  GameResumedEventForObserver = "GameResumedEventForObserver",
  RoundStartedEvent = "RoundStartedEvent",
  RoundEndedEventForBot = "RoundEndedEventForBot",
  RoundEndedEventForObserver = "RoundEndedEventForObserver",
  ChangeTps = "ChangeTps",
  TpsChangedEvent = "TpsChangedEvent",
  BotPolicyUpdate = "BotPolicyUpdate",
  BotDeathEvent = "BotDeathEvent",
  BotHitBotEvent = "BotHitBotEvent",
  BotHitWallEvent = "BotHitWallEvent",
  BulletFiredEvent = "BulletFiredEvent",
  BulletHitBotEvent = "BulletHitBotEvent",
  BulletHitBulletEvent = "BulletHitBulletEvent",
  BulletHitWallEvent = "BulletHitWallEvent",
  HitByBulletEvent = "HitByBulletEvent",
  ScannedBotEvent = "ScannedBotEvent",
  SkippedTurnEvent = "SkippedTurnEvent",
  TickEventForBot = "TickEventForBot",
  TickEventForObserver = "TickEventForObserver",
  WonRoundEvent = "WonRoundEvent",
  TeamMessageEvent = "TeamMessageEvent",
  StartGame = "StartGame",
  StopGame = "StopGame",
  PauseGame = "PauseGame",
  ResumeGame = "ResumeGame",
  NextTurn = "NextTurn",
}
