package dev.robocode.tankroyale.common.rules

/**
 * Immutable preset definition for a game type. Provides the default parameter values and locked
 * flags for each built-in game type. Transport-layer types (server Duration, client Int micros)
 * are deliberately avoided — consumers convert from these primitive values.
 */
data class GameTypePreset(
    val gameType: GameType,
    val arenaWidth: Int,
    val isArenaWidthLocked: Boolean,
    val arenaHeight: Int,
    val isArenaHeightLocked: Boolean,
    val minNumberOfParticipants: Int,
    val isMinNumberOfParticipantsLocked: Boolean,
    val maxNumberOfParticipants: Int?,
    val isMaxNumberOfParticipantsLocked: Boolean,
    val numberOfRounds: Int,
    val isNumberOfRoundsLocked: Boolean,
    val gunCoolingRate: Double,
    val isGunCoolingRateLocked: Boolean,
    val maxInactivityTurns: Int,
    val isMaxInactivityTurnsLocked: Boolean,
    /** Turn timeout in microseconds. */
    val turnTimeoutMicros: Int,
    val isTurnTimeoutLocked: Boolean,
    /** Ready timeout in microseconds. */
    val readyTimeoutMicros: Int,
    val isReadyTimeoutLocked: Boolean,
    val defaultTurnsPerSecond: Int,
)

/** Built-in game type presets keyed by [GameType]. */
val GAME_TYPE_PRESETS: Map<GameType, GameTypePreset> = mapOf(
    GameType.CUSTOM to GameTypePreset(
        gameType = GameType.CUSTOM,
        arenaWidth = 800,
        isArenaWidthLocked = false,
        arenaHeight = 600,
        isArenaHeightLocked = false,
        minNumberOfParticipants = 2,
        isMinNumberOfParticipantsLocked = false,
        maxNumberOfParticipants = null,
        isMaxNumberOfParticipantsLocked = false,
        numberOfRounds = 10,
        isNumberOfRoundsLocked = false,
        gunCoolingRate = 0.1,
        isGunCoolingRateLocked = false,
        maxInactivityTurns = 450,
        isMaxInactivityTurnsLocked = false,
        turnTimeoutMicros = 30_000,
        isTurnTimeoutLocked = false,
        readyTimeoutMicros = DEFAULT_READY_TIMEOUT_MICROS,
        isReadyTimeoutLocked = false,
        defaultTurnsPerSecond = 30,
    ),
    GameType.CLASSIC to GameTypePreset(
        gameType = GameType.CLASSIC,
        arenaWidth = 800,
        isArenaWidthLocked = true,
        arenaHeight = 600,
        isArenaHeightLocked = true,
        minNumberOfParticipants = 2,
        isMinNumberOfParticipantsLocked = true,
        maxNumberOfParticipants = null,
        isMaxNumberOfParticipantsLocked = true,
        numberOfRounds = 10,
        isNumberOfRoundsLocked = true,
        gunCoolingRate = 0.1,
        isGunCoolingRateLocked = true,
        maxInactivityTurns = 450,
        isMaxInactivityTurnsLocked = true,
        turnTimeoutMicros = 30_000,
        isTurnTimeoutLocked = false,
        readyTimeoutMicros = DEFAULT_READY_TIMEOUT_MICROS,
        isReadyTimeoutLocked = false,
        defaultTurnsPerSecond = 30,
    ),
    GameType.MELEE to GameTypePreset(
        gameType = GameType.MELEE,
        arenaWidth = 1000,
        isArenaWidthLocked = true,
        arenaHeight = 1000,
        isArenaHeightLocked = true,
        minNumberOfParticipants = 10,
        isMinNumberOfParticipantsLocked = true,
        maxNumberOfParticipants = null,
        isMaxNumberOfParticipantsLocked = false,
        numberOfRounds = 10,
        isNumberOfRoundsLocked = false,
        gunCoolingRate = 0.1,
        isGunCoolingRateLocked = false,
        maxInactivityTurns = 450,
        isMaxInactivityTurnsLocked = false,
        turnTimeoutMicros = 30_000,
        isTurnTimeoutLocked = false,
        readyTimeoutMicros = DEFAULT_READY_TIMEOUT_MICROS,
        isReadyTimeoutLocked = false,
        defaultTurnsPerSecond = 30,
    ),
    GameType.ONE_VS_ONE to GameTypePreset(
        gameType = GameType.ONE_VS_ONE,
        arenaWidth = 800,
        isArenaWidthLocked = true,
        arenaHeight = 600,
        isArenaHeightLocked = true,
        minNumberOfParticipants = 2,
        isMinNumberOfParticipantsLocked = true,
        maxNumberOfParticipants = 2,
        isMaxNumberOfParticipantsLocked = true,
        numberOfRounds = 10,
        isNumberOfRoundsLocked = false,
        gunCoolingRate = 0.1,
        isGunCoolingRateLocked = false,
        maxInactivityTurns = 450,
        isMaxInactivityTurnsLocked = false,
        turnTimeoutMicros = 30_000,
        isTurnTimeoutLocked = false,
        readyTimeoutMicros = DEFAULT_READY_TIMEOUT_MICROS,
        isReadyTimeoutLocked = false,
        defaultTurnsPerSecond = 30,
    ),
)
