# Sphinx configuration for Robocode Tank Royale Bot API (Python)
# This configuration enables Google-style docstrings via Napoleon.

from __future__ import annotations

import os
import sys
from pathlib import Path

# -- Project information -----------------------------------------------------

def _find_repo_root(start: Path) -> Path:
    p = start.resolve()
    for parent in [p, *p.parents]:
        if (parent / "VERSION").exists():
            return parent
    # Fallback to start if VERSION not found
    return p

_here = Path(__file__).resolve()
_repo_root = _find_repo_root(_here)

# Ensure Python package is importable during autodoc. The Sphinx source is copied under
# build/sphinx/source, so we locate the python project dir (which contains VERSION) and
# add both src/ and src/robocode_tank_royale to sys.path to support imports like
# 'robocode_tank_royale.bot_api' and the apidoc-generated 'bot_api.*' modules.
_python_project_dir = _repo_root
_src_dir = _python_project_dir / "src"
_sys_paths = [
    _src_dir,                          # for 'robocode_tank_royale.*'
    _src_dir / "robocode_tank_royale"  # for 'bot_api.*' generated by apidoc
]
for p in _sys_paths:
    sp = str(p)
    if os.path.isdir(sp) and sp not in sys.path:
        sys.path.insert(0, sp)

project = "Robocode Tank Royale Bot API (Python)"

# Read version from top-level VERSION file if present
version_file = _repo_root / "VERSION"
release = version = version_file.read_text(encoding="utf-8").strip() if version_file.exists() else "0.0.0"

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",  # Google/NumPy style docstrings
    "sphinx.ext.viewcode",
]

# Have autodoc include members by default so method names are visible even if undocumented
autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "inherited-members": True,
    "show-inheritance": True,
}
# Keep method order as in source files for easier navigation
autodoc_member_order = "bysource"
# Optional: shorten headings by omitting fully-qualified module name prefixes
add_module_names = False

# Napoleon settings for Google-style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = False
napoleon_use_param = True
napoleon_use_ivar = True

templates_path = ["_templates"]
exclude_patterns: list[str] = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
]

# -- Options for HTML output -------------------------------------------------

# Try to use the Awesome Sphinx Theme (sphinxawesome_theme) if it's installed.
# If not installed, warn and fall back to the default 'alabaster' theme so
# documentation builds don't fail unexpectedly.
#
# Install the theme with:
#   pip install sphinxawesome-theme
#
# See: https://pypi.org/project/sphinxawesome-theme/
import warnings

html_theme = "alabaster"
html_theme_path: list[str] = []

try:
    import sphinxawesome_theme  # type: ignore
except Exception:
    warnings.warn(
        "sphinxawesome_theme not found; falling back to 'alabaster'. "
        "To use the Awesome theme install it with: pip install sphinxawesome-theme",
        UserWarning,
    )
    html_theme = "alabaster"
else:
    html_theme = "sphinxawesome_theme"
    # Some theme packages expose get_html_theme_path(); if available, add it so
    # Sphinx can locate theme resources (older setups sometimes require this).
    get_path = getattr(sphinxawesome_theme, "get_html_theme_path", None)
    if callable(get_path):
        try:
            theme_path = get_path()
            if theme_path:
                html_theme_path = [theme_path]
        except Exception:
            # If retrieving the theme path fails, ignore and rely on Sphinx's
            # normal theme discovery (the theme is installed in site-packages).
            pass

# Minimal theme options placeholder; customize as needed (see theme docs).
html_theme_options = {
    # Example options you can enable/adjust:
    # "github_user": "your-gh-username",
    # "github_repo": "your-repo",
    # "logo": "logo.png",
}

html_static_path = ["_static"]
